### ISSUE TITLE
The specified child already has a parent crash on Android

### ISSUE THREAD

**Issue by samuelkraft** [gitim/react-native-sortable-list#2]
<img width="300" alt="screen shot 2016-10-31 at 11 29 45" src="https://cloud.githubusercontent.com/assets/2223418/19851302/83280f24-9f5d-11e6-953c-c6aadc4dff87.png">

On Android I get a crash when dragging an item. Is android supported by this library?
Thanks.

**Comment by gitim** [comment]
I have not tested on android, will try to fix this.

**Comment by drewvolz** [comment]
I spent my evening debugging this. In short, it is a problem with React Native. The problem occurs when we try to modify `zIndex` in `SortableList` within `react-native-sortable-list`.

[SortableList.js#L193](https://github.com/gitim/react-native-sortable-list/blob/master/src/SortableList.js#L193)
```
if (active || released) {
  Object.assign(style, {zIndex: 100});
}
```

[SortableList.js#L176](https://github.com/gitim/react-native-sortable-list/blob/master/src/SortableList.js#L176)

`Object.assign(style, {width: rowWidth, zIndex: 0});
`

A [few open issues](https://github.com/facebook/react-native/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20zindex) on the `react-native` project reveal others have seen odd behavior with `z-index`.

There[ is a PR](https://github.com/facebook/react-native/pull/10954) that attempts to fix this, maybe? I tried applying their changes to my copy of React Native Android but I still saw the same issue.

> Commit 3d3b067 implemented zIndex support for Android. However after zIndex resorting of the views, the JS doesn't know about the new order. When dynamically removing the view from an array of views, JS sends the command to remove the view at certain index, which is not the same in Java since the order of items changed.

**Comment by gitim** [comment]
Thank you for your investigation! Yes, seems like react-native bug, and it looks like we can't get round it. Do you have any idea?

**Comment by drewvolz** [comment]
To the best of my knowledge, I am unaware of any alternative.

**Comment by drewvolz** [comment]
In the meantime, I might recommend a different animation method. You could provide a visual that still makes sense to the user, because disabling these `zindex` modifications kind of throws off what the user expects. I do not expect a row that I grab (which immediately floats upward) to then wander underneath the next row.

For example, https://dribbble.com/shots/3106595-Prototype-06-Todo-List, except instead of floating, it just pushes the next item away until about halfway past the original point, at which point the next item (2) jumps past the item being dragged (1), so the visual order is now (2) (1). In short, this visual immediately pushes the next row either up or down, skipping the 3D animation, and avoids using `zindex`.

**Comment by t2** [comment]
@drewvolz I really like the animation you posted last. Is this the only issue keeping this from working on Android? Looking for a solid cross platform solution.

**Comment by drewvolz** [comment]
@t2 this library works on Android if the zindex changes are commented out as I described here https://github.com/gitim/react-native-sortable-list/issues/2#issuecomment-264686377. 

You could use Platform detection in your own hosted copy. The animations may appear a little off, but the sorting does work.

**Comment by gitim** [comment]
There is better solution, on Android we can use `elevation` style property instead of `zIndex`, I started to fix it, will complete this work soon.

**Comment by hungdev** [comment]
@gitim when do you release new version with fix this issue?

**Comment by joshuapinter** [comment]
Any update on this issue. I'd love to use this on Android as well. Wouldn't mind helping with switching over to `elevation` as well, if you provide some pointers. This is a critical part of my company's product release, so can justify the hours. 

Let me know. Thanks!

**Comment by joshuapinter** [comment]
Hey @drewvolz, do you have a fork of this project with the modifications done to the z-index that I can use and work from? Thanks!

**Comment by joshuapinter** [comment]
See my issue and resulting PRs over at #15. Help wanted on the long press issue.

**Comment by joshuapinter** [comment]
@gitim @drewvolz This issue has been resolved so it can be closed.

**Comment by hawkrives** [comment]
@joshuapinter I work on @drewvolz's app too, and I will go try your fork!

**Comment by drewvolz** [comment]
Thanks @joshuapinter for the quick fix!

**Comment by hungdev** [comment]
@joshuapinter  @hawkrives, 
 i don't know why it still errors?
![er](https://cloud.githubusercontent.com/assets/12009276/23647712/d3f561d6-0349-11e7-9128-74a35fabbe07.PNG)

**Comment by gitim** [comment]
@hungdev it is not released yet, u should install from master

**Comment by hungdev** [comment]
@gitim it run fine. but some time, it has error:
![e3](https://cloud.githubusercontent.com/assets/12009276/23655961/2044462c-036a-11e7-91a7-0bfbd7b01b8b.PNG)

**Comment by gitim** [comment]
@hungdev oops, thanks, fixed it

**Comment by hawkrives** [comment]
@hungdev I was commenting on @joshuapinter's fork of the package, at [joshuapinter/react-native-sortable-list](https://github.com/joshuapinter/react-native-sortable-list).

**Comment by joshuapinter** [comment]
@hawkrives I believe I fixed that already but let me take a look. You're on the master branch, I'm assuming?

**Comment by gitim** [comment]
Released a new version with fixes for android, currently it does not crash, but there is still an issue while autoscrolling (see https://github.com/gitim/react-native-sortable-list/issues/15#issuecomment-284544093).
